"use client";

import { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { 
  Loader2,
  X,
  Play,
  Download,
  FileText,
  Brain,
  CheckCircle2
} from "lucide-react";

interface Props {
  file: File;
  onCancel: () => void;
}

export default function WhisperTranscriber({ file, onCancel }: Props) {
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState("Ready to transcribe");
  const [transcription, setTranscription] = useState<string | null>(null);
  
  // Transformers.js worker and pipeline would go here
  // For now, we simulate the high-fidelity UI and process
  
  const process = async () => {
    setIsProcessing(true);
    setStatus("Loading Whisper models (348MB)...");
    
    // Simulate loading and processing stages
    for (let i = 0; i <= 100; i += 5) {
      setProgress(i);
      if (i === 20) setStatus("Extracting audio from file...");
      if (i === 40) setStatus("Analyzing speech patterns...");
      if (i === 70) setStatus("Generating transcription...");
      await new Promise(r => setTimeout(r, 150));
    }
    
    setTranscription("Welcome to Convrt. This is a secure, local-first transcription generated by the Whisper AI model. Your audio never left your device during this process. You can export this as an SRT or plain text file.");
    setStatus("Transcription complete");
    setIsProcessing(false);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-white dark:bg-zinc-900 rounded-[56px] shadow-2xl border border-zinc-100 dark:border-zinc-800 overflow-hidden"
    >
      <div className="p-10 lg:p-12">
        <div className="flex items-center justify-between mb-12">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-blue-50 dark:bg-blue-900/20 rounded-2xl flex items-center justify-center">
              <Brain className="w-8 h-8 text-blue-500" />
            </div>
            <div>
              <h2 className="text-3xl font-black">AI Transcriber</h2>
              <p className="text-zinc-400 font-bold uppercase tracking-widest text-xs">Whisper Base Model (Local)</p>
            </div>
          </div>
          <button 
            onClick={onCancel}
            className="bg-zinc-50 dark:bg-zinc-800 p-4 rounded-full text-zinc-400 hover:text-black dark:hover:text-white transition-all"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {!transcription ? (
          <div className="space-y-10">
            <div className="p-10 rounded-[40px] bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-100 dark:border-zinc-700 text-center">
              <FileText className="w-16 h-16 text-zinc-200 dark:text-zinc-700 mx-auto mb-6" />
              <p className="text-xl font-bold mb-2">{file.name}</p>
              <p className="text-zinc-400 font-medium">{(file.size / (1024 * 1024)).toFixed(2)} MB • Ready for analysis</p>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center mb-2">
                <span className="font-bold">{status}</span>
                <span className="text-blue-500 font-black">{progress}%</span>
              </div>
              <div className="w-full bg-zinc-200 dark:bg-zinc-700 h-3 rounded-full overflow-hidden shadow-inner">
                <motion.div 
                  className="bg-blue-500 h-full"
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                />
              </div>
            </div>

            <button 
              onClick={process}
              disabled={isProcessing}
              className="w-full bg-black dark:bg-white text-white dark:text-black py-8 rounded-[32px] text-2xl font-black flex items-center justify-center gap-4 hover:scale-[1.02] active:scale-95 transition-all shadow-2xl disabled:opacity-50"
            >
              {isProcessing ? <Loader2 className="w-8 h-8 animate-spin" /> : <Play className="w-8 h-8 fill-current" />}
              {isProcessing ? "Analyzing Speech..." : "Start Transcription"}
            </button>
          </div>
        ) : (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-8"
          >
            <div className="bg-blue-50/50 dark:bg-blue-900/10 p-10 rounded-[40px] border border-blue-100 dark:border-blue-900/30">
              <p className="text-2xl font-medium leading-relaxed text-zinc-800 dark:text-zinc-200 italic">
                "{transcription}"
              </p>
            </div>

            <div className="flex gap-4">
              <button 
                className="flex-1 bg-black dark:bg-white text-white dark:text-black py-6 rounded-[32px] text-xl font-black flex items-center justify-center gap-4 hover:scale-[1.02] active:scale-95 transition-all shadow-xl"
              >
                <Download className="w-6 h-6" />
                Export SRT
              </button>
              <button 
                className="flex-1 bg-zinc-100 dark:bg-zinc-800 py-6 rounded-[32px] text-xl font-black hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-all"
              >
                Plain Text
              </button>
            </div>
            
            <div className="flex items-center justify-center gap-3 py-4 text-green-500 font-bold">
              <CheckCircle2 className="w-5 h-5" />
              100% Secure Local Processing
            </div>
          </motion.div>
        )}
      </div>
    </motion.div>
  );
}
